--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.5 (Ubuntu 17.5-1.pgdg24.04+1)

-- Started on 2025-08-03 22:43:13 WAT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16802)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    is_low_stock boolean NOT NULL,
    low_stock_threshold integer NOT NULL,
    name character varying(100) NOT NULL,
    price numeric(38,2) NOT NULL,
    sku character varying(255),
    stock_quantity integer NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT products_low_stock_threshold_check CHECK ((low_stock_threshold >= 1)),
    CONSTRAINT products_stock_quantity_check CHECK ((stock_quantity >= 0))
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16801)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3440 (class 0 OID 16802)
-- Dependencies: 218
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, category, created_at, description, is_low_stock, low_stock_threshold, name, price, sku, stock_quantity, updated_at) FROM stdin;
1	Electronics	2025-05-04 14:34:56.578628	Latest model with 6.5 inch display and improved camera	t	3	Smartphone XYZ	749.99	PHN-XYZ-001	2	2025-05-04 14:40:02.986046
3	furniture	2025-08-03 22:41:35.966701	furniture you need to relas	f	20	chair	500.00	3446rt	104	2025-08-03 22:41:35.966771
\.


--
-- TOC entry 3446 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 3, true);


--
-- TOC entry 3293 (class 2606 OID 16810)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


-- Completed on 2025-08-03 22:43:13 WAT

--
-- PostgreSQL database dump complete
--

